name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Clippy
      run: rustup component add clippy

    - name: Run cargo clippy
      run: cargo clippy --all -- -D warnings

    - name: fmt check
      run: cargo fmt --all -- --check
    
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
